### ISSUE TITLE
APT repo

### ISSUE THREAD

**Issue by samip5** [astr0n8t/vyos-tailscale-gha#46]
Hi there,

I'm working  on a new APT repo for VyOS so that builds start to work again.
CI is here: https://ci.d10.fi and apt repo is at: https://vy-deb.d10.fi.
GPG key is at: https://vy-deb.d10.fi./d10_public.key. The key is used to only sign the repository.

**Comment by astr0n8t** [comment]
Builds are working just fine unless there's some news I missed.  I had to do some work the other day to get it back working but was related to a build script change in vyos-build.

**Comment by astr0n8t** [comment]
Ah I see now, [heres the blog post for reference](https://blog.vyos.io/community-contributors-userbase-and-lts-builds) What I'll probably do is just switch to building rolling release again which is kind of a pain only because they're constantly changing the CLI commands.  That's honestly the only reason I was tracking the sagitta branch.  I'll have to do some more testing later to see if the repo works on the rolling release or if they're just completely blocking anyone from using their repos for whatever reason.

For normal plain vyos builds, I still need to build myself rather than use their images because I need proper cloud-init support that works.

**Comment by samip5** [comment]
The problem is that rolling images don't work either if it uses their APT repo. At least for 1.4 rolling.

**Comment by astr0n8t** [comment]
Ah gotcha, I'm tracking the changes via #47 Using the 1.5 rolling repo here:
```
https://rolling-packages.vyos.net/current current/main
```

**Comment by samip5** [comment]
Ah, okay so 1.5 rolling works then. Just 1.4 rolling doesn't.

**Comment by astr0n8t** [comment]
By 1.4 rolling do you just mean building off of the sagitta branch?  Pretty sure the vyos folks just consider that "LTS" which is why it wouldn't work.

**Comment by samip5** [comment]
Yeah, it seems their whole build system doesn't understand the concept of rolling and LTS in reality.

**Comment by astr0n8t** [comment]
Yeah, its never been a reproducible LTS build which is disappointing.  Again only problem I have with rolling is that they change the CLI syntax often.  If they left that alone and only added new commands it would be fine, but I fear I'm going to be playing whackamole with my ansible role in the future.
